"""Adversarial / edge-case stubs for the v0.3 three-layer architecture.

Generated by the v0.3 audit. Each test is `@pytest.mark.skip`-marked with a
reason and TODO. The audit's job ends at stubbing; converting these to
real tests is follow-up work driven by `docs/v03-audit-report.md`.

Naming maps to `docs/v03-audit-gaps.md`: WM-* working memory, W-* wiki,
SA-* session archive, B-* briefing, API-* public API, INT-* integration.

Do NOT remove a skip without first deciding what the assertion should be —
some of these stubs document open architectural questions, not just
missing tests. See the audit report for which to implement first.
"""

from __future__ import annotations

import pytest

# ---------- working memory ----------


@pytest.mark.skip(reason="WM-1: start_session called twice with same session_id; clobber/append/error?")
def test_working_memory_start_twice_same_session_id() -> None:
    """TODO: WorkingMemory.start with an in-progress session_id silently clobbers.
    Decide intended behavior (refuse / resume / clobber-with-warning) and assert it.
    """


@pytest.mark.skip(reason="WM-2: expired session files are not cleaned up; load returns None but file persists")
def test_expired_session_files_are_cleaned_up() -> None:
    """TODO: Persist a session, advance clock past 24h TTL, call WorkingMemory.load → None,
    then assert the .json file was unlinked. Currently disk fills with zombies.
    """


@pytest.mark.skip(reason="WM-3: _truncate_tokens budget math allows ~3x the requested token count")
def test_get_context_respects_token_budget() -> None:
    """TODO: Build a WorkingMemory with very long observations, call get_context(max_tokens=100),
    tokenize the result, assert <= 100 actual tokens (use tiktoken or word*1.33 heuristic).
    """


@pytest.mark.skip(reason="WM-4: concurrent add_observation calls race; lost updates")
def test_concurrent_add_observation_does_not_lose_updates() -> None:
    """TODO: Spawn 50 threads each calling wm.add_observation; assert final list has 50 items.
    Currently the read-modify-write _persist races and loses some.
    """


@pytest.mark.skip(reason="WM-5: pydantic ValidationError leaks instead of icarus_memory.ValidationError")
def test_empty_observation_raises_icarus_validation_error() -> None:
    """TODO: wm.add_observation("") should raise icarus_memory.ValidationError, not pydantic.ValidationError.
    """


@pytest.mark.skip(reason="WM-7: observation list grows unbounded; quadratic write cost")
def test_observation_count_has_a_cap_or_documents_unbounded() -> None:
    """TODO: Either enforce a max-observations cap with deterministic eviction, or document
    that the cost grows linearly per-write and quadratically over the whole session.
    """


@pytest.mark.skip(reason="WM-A3: session file path is keyed by session_id only, not (agent_id, session_id)")
def test_session_files_partition_by_agent() -> None:
    """TODO: agent A creates session 'sess1', agent B creates session 'sess1' on same fabric.
    Currently second clobbers first. Assert either disjoint storage or explicit error.
    """


# ---------- wiki ----------


@pytest.mark.skip(reason="W-1: wiki body is a snapshot; goes stale after entry verify/contradict/supersede")
def test_wiki_body_reflects_current_entry_state_or_documents_staleness() -> None:
    """TODO: write entry → add to wiki → contradict the entry → re-read wiki page.
    Currently the rendered body still shows the old status. Either re-render on read,
    invalidate, or document staleness as a known limitation.
    """


@pytest.mark.skip(reason="W-2: classify_and_add race loses concurrent appends to same page")
def test_classify_and_add_concurrent_writes_do_not_lose_entries() -> None:
    """TODO: 10 threads call wiki.classify_and_add for the same page; assert all 10 entry IDs end up linked.
    """


@pytest.mark.skip(reason="W-A2: wiki pages are global with no agent scope")
def test_wiki_cross_agent_access_is_documented_or_scoped() -> None:
    """TODO: agent A creates a wiki page; agent B opens the same fabric; can B see it?
    If yes (current behavior), the spec must document this as 'wiki = shared knowledge'.
    If not, add agent scoping. Test asserts the chosen behavior explicitly.
    """


@pytest.mark.skip(reason="W-A3: wiki has no lifecycle; can't supersede a wiki page")
def test_wiki_page_supersession_or_deletion() -> None:
    """TODO: Once a wiki page exists with a wrong path/title, there's no API to merge or rename.
    Either add wiki.supersede_page / wiki.merge_pages, or document that wiki pages are immutable.
    """


@pytest.mark.skip(reason="W-4: every mem.write triggers an OpenAI call via _classify_wiki_after_write")
def test_wiki_classification_can_be_disabled_at_write_time() -> None:
    """TODO: Construct IcarusMemory(enable_wiki_classification=False) (or similar); assert mem.write
    does NOT make a network call. Currently the slow path always runs.
    """


@pytest.mark.skip(reason="W-9: wiki page entries list is unbounded")
def test_wiki_page_entry_list_has_a_cap_or_pagination() -> None:
    """TODO: Add 10k entries to one page; measure write time and rendered body size.
    Either enforce a cap with eviction or document growth characteristics.
    """


@pytest.mark.skip(reason="W-10: _classify_entry prompt includes ALL existing pages")
def test_classify_entry_prompt_does_not_blow_context_window() -> None:
    """TODO: Create 1000 wiki pages, call _classify_entry on a new entry, assert prompt token count
    is bounded. Currently the prompt grows linearly with wiki size.
    """


@pytest.mark.skip(reason="W-11: no wiki delete/merge/rename API")
def test_wiki_page_can_be_deleted_or_merged() -> None:
    """TODO: A bad LLM classification creates 'desicions/auth' (typo). There's no recovery API.
    Add WikiManager.delete_page / merge_pages / rename_page or document immutability.
    """


@pytest.mark.skip(reason="W-12: WikiPage Pydantic extra='forbid' breaks future schema migration")
def test_wiki_page_with_unknown_frontmatter_field_is_tolerated_or_migrated() -> None:
    """TODO: Write a wiki page file by hand with an extra 'tags: []' field. Currently
    WikiManager.get_page raises StoreError. Match Entry's lazy-migration approach in store.py.
    """


# ---------- session archive ----------


@pytest.mark.skip(reason="SA-1: corrupted session JSON crashes search and iter_agent_sessions")
def test_corrupted_session_json_is_skipped_with_warning() -> None:
    """TODO: archive a session, corrupt its JSON on disk, call archive.search(...) →
    currently raises Pydantic ValidationError on the bad file. Should skip-and-warn.
    """


@pytest.mark.skip(reason="SA-2: search tiebreak sorts by oldest archived_at, not newest")
def test_search_tiebreak_returns_newest_first() -> None:
    """TODO: archive two sessions with identical content but different archived_at; assert the
    NEWER one comes first when scores tie. Currently older-first.
    """


@pytest.mark.skip(reason="SA-3: empty query returns all sessions scored 1")
def test_empty_search_query_returns_empty_or_raises() -> None:
    """TODO: archive.search("", agent_id="A") currently returns up to `limit` sessions (all scored 1).
    Decide: return [], or raise ValidationError. Implement and assert.
    """


@pytest.mark.skip(reason="SA-4: filter_failed=True semantics are inverted (keeps failed instead of filtering them)")
def test_filter_failed_param_naming_or_behavior() -> None:
    """TODO: Rename to had_failure or only_with_failed_attempts. Or invert semantics.
    Pick one and add a clarifying test.
    """


@pytest.mark.skip(reason="SA-5: re-archiving same (agent, session) clobbers silently")
def test_re_archive_same_session_warns_or_errors() -> None:
    """TODO: archive(wm) twice with same session; second silently overwrites. Decide: error,
    skip, or merge with audit trail. Assert chosen behavior.
    """


@pytest.mark.skip(reason="SA-7: no archive deletion/retention API")
def test_archive_delete_or_compact_api() -> None:
    """TODO: Once archived, sessions live forever. Add archive.delete(agent, session) or compact() —
    whichever the project decides — and test it.
    """


# ---------- briefing ----------


@pytest.mark.skip(reason="B-1: _recent_superseded filters by entry.timestamp not by supersession time")
def test_recent_superseded_uses_supersession_time_not_write_time() -> None:
    """TODO: Write an entry 60 days ago, supersede it today; current code excludes it from
    'recent superseded' because the 30-day window is anchored on entry.timestamp.
    Assert it appears in the briefing.
    """


@pytest.mark.skip(reason="B-3: 10s LLM timeout exceeds 8s cold-cache budget")
def test_briefing_cold_cache_meets_8s_budget_with_realistic_timeout() -> None:
    """TODO: Mock OpenAI to take 9s; assert briefing.generate either returns within 8s
    via fallback or documents the >8s outcome. Currently exceeds budget silently.
    """


@pytest.mark.skip(reason="B-4: cache mid-flight staleness")
def test_briefing_cache_mid_flight_wiki_update_is_safe() -> None:
    """TODO: Start briefing.generate, update wiki on another thread before generate completes,
    assert next briefing.generate sees the update. Currently first call serves stale.
    """


@pytest.mark.skip(reason="B-5: cache TTL = 1h; no test asserts expiry")
def test_briefing_cache_expires_after_ttl() -> None:
    """TODO: Generate briefing, fast-forward clock past 1h, generate again, assert
    different cache_key (or different created_at). Currently no test exercises TTL.
    """


@pytest.mark.skip(reason="B-8: corrupt briefing cache crashes _read_cache")
def test_corrupt_cache_file_is_treated_as_miss() -> None:
    """TODO: Write garbage to a cache file, call get_briefing → currently raises
    Pydantic ValidationError. Should treat as cache miss and regenerate.
    """


@pytest.mark.skip(reason="B-11: briefing prompt unbounded by session size")
def test_briefing_prompt_token_count_bounded() -> None:
    """TODO: Archive a session with 10k observations; call get_briefing; assert prompt
    sent to LLM is under model context window (e.g., 32k tokens for gpt-4o-mini).
    """


@pytest.mark.skip(reason="B-12: briefing cache files accumulate forever")
def test_briefing_cache_compaction_or_lru() -> None:
    """TODO: Generate 100 briefings with different (agent, task) pairs, assert disk use
    stays bounded or there is an explicit compaction API.
    """


# ---------- public API ----------


@pytest.mark.skip(reason="API-A1: mem.write always triggers wiki classification with no opt-out")
def test_write_does_not_call_openai_when_classification_disabled() -> None:
    """TODO: IcarusMemory(enable_wiki_classification=False) (or similar); patch urllib to
    record any HTTPS requests; assert mem.write makes none. Currently no opt-out exists.
    """


@pytest.mark.skip(reason="API-A2: end_session double-links the session_summary entry")
def test_end_session_does_not_double_link_session_summary() -> None:
    """TODO: end_session(promote_to_wiki=['decisions/auth']) writes a session_summary entry;
    that write also triggers _classify_wiki_after_write. Currently the entry ends up in
    BOTH the auto-classified page AND the explicit page. Assert only one (the explicit one).
    """


@pytest.mark.skip(reason="API-A3: start_session always generates a briefing; no opt-out")
def test_start_session_can_skip_briefing() -> None:
    """TODO: mem.start_session('agent', 'task', briefing=False) returns just WorkingMemory.
    Currently always runs briefing.generate (LLM cost on every session start).
    """


@pytest.mark.skip(reason="API-A4: no resume-existing-session API")
def test_resume_existing_session_via_public_api() -> None:
    """TODO: After a process restart, the public API should let you reach an in-progress
    WorkingMemory by session_id. Currently you must reach into WorkingMemory.load directly.
    """


@pytest.mark.skip(reason="API-1: end_session partial-failure leaves inconsistent state")
def test_end_session_partial_failure_is_atomic_or_rolls_back() -> None:
    """TODO: Mock store.write to fail on the second wiki promotion; assert end_session either
    rolls back the archive or surfaces a clear partial-failure error.
    """


@pytest.mark.skip(reason="API-2: end_session called twice clobbers archive")
def test_end_session_idempotent_or_errors() -> None:
    """TODO: Call mem.end_session(wm, ...) twice; second should error or no-op, not clobber.
    """


@pytest.mark.skip(reason="API-7: __version__ still says 0.2.0")
def test_version_string_is_v03() -> None:
    """TODO: assert icarus_memory.__version__ == '0.3.0'. Currently '0.2.0'.
    Trivial fix; flagging in stub form per audit policy.
    """


# ---------- integration ----------


@pytest.mark.skip(reason="INT-3: integration test only exercises the offline template path")
def test_integration_with_live_llm_path() -> None:
    """TODO: With a mocked-as-success OpenAI; assert briefing.cost_usd > 0,
    briefing.content reflects LLM output, AND cross-agent privacy still holds.
    """


@pytest.mark.skip(reason="INT-1: no concurrent-session integration test")
def test_two_concurrent_sessions_same_agent() -> None:
    """TODO: agent starts session A, then session B without ending A. Both sessions get
    distinct session_ids; ending one doesn't affect the other. Assert isolation.
    """


@pytest.mark.skip(reason="W-A2 + INT cross-cutting: cross-agent leak via wiki promotion is undocumented")
def test_cross_agent_wiki_visibility_is_explicit_in_docs() -> None:
    """TODO: Agent A end_session(promote_to_wiki=['secrets/api-key']). Agent B opens the
    same fabric. Asserts what the project decides: either B sees the page (current behavior,
    with explicit doc) or it's filtered out by some mechanism. Test pinned to chosen behavior.
    """
